/* eslint-disable import/prefer-default-export */

export const SET_RUNTIME_VARIABLE = 'SET_RUNTIME_VARIABLE';

export const SET_NEW_LOCALIZATION = 'SET_NEW_LOCALIZATION';

export const SET_NEW_ROUTER_OBJECT_ARGUMENT = 'SET_NEW_ROUTER_OBJECT_ARGUMENT';
export const SET_NEW_ROUTER_TOPIC_ARGUMENT = 'SET_NEW_ROUTER_TOPIC_ARGUMENT';

export const SET_NEW_SOCKET_STATUS = 'SET_NEW_SOCKET_STATUS';

export const SET_NEW_USER_AUTHENTICATED = 'SET_NEW_USER_AUTHENTICATED';
export const SET_LOGOUT_USER = 'SET_LOGOUT_USER';
