module.exports = [

  { value:'ad', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag ad", label:"Andorra"},
  { value:'ae', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag ae", label:"United Arab Emirates"},
  { value:'af', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag af", label:"Afghanistan"},
    { value:'ag', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag ag", label:"Antigua and Barbuda"},
  { value:'ai', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag ai", label:"Anguilla"},
    { value:'al', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag al", label:"Albania"},
    { value:'am', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag am", label:"Armenia"},
    { value:'an', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag an", label:"Netherlands Antilles"},
  { value:'ao', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag ao", label:"Angola"},
    { value:'aq', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag aq", label:"Antarctica"},
    { value:'ar', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag ar", label:"Argentina"},
    { value:'as', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag as", label:"American Samoa"},
  { value:'at', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag at", label:"Austria"},
    { value:'au', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag au", label:"Australia"},
    { value:'aw', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag aw", label:"Aruba"},
    { value:'ax', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag ax", label:"Aland Islands"},
  { value:'az', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag az", label:"Azerbaijan"},
    { value:'ba', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag ba", label:"Bosnia and Herzegovina"},
  { value:'bb', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag bb", label:"Barbados"},
    { value:'bd', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag bd", label:"Bangladesh"},
    { value:'be', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag be", label:"Belgium"},
    { value:'bf', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag bf", label:"Burkina Faso"},
  { value:'bg', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag bg", label:"Bulgaria"},
    { value:'bh', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag bh", label:"Bahrain"},
    { value:'bi', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag bi", label:"Burundi"},
    { value:'bj', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag bj", label:"Benin"},
    { value:'bm', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag bm", label:"Bermuda"},
    { value:'bn', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag bn", label:"Brunei Darussalam"},
  { value:'bo', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag bo", label:"Bolivia"},
    { value:'br', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag br", label:"Brazil"},
    { value:'bs', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag bs", label:"Bahamas"},
    { value:'bt', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag bt", label:"Bhutan"},
    { value:'bv', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag bv", label:"Bouvet Island"},
  { value:'bw', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag bw", label:"Botswana"},
    { value:'by', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag by", label:"Belarus"},
    { value:'bz', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag bz", label:"Belize"},
    { value:'ca', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag ca", label:"Canada"},
    { value:'cc', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag cc", label:"Cocos (Keeling) Islands"},
  { value:'cd', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag cd", label:"Democratic Republic of the Congo"},
  { value:'cf', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag cf", label:"Central African Republic"},
  { value:'cg', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag cg", label:"Congo"},
    { value:'ch', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag ch", label:"Switzerland"},
    { value:'ci', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag ci", label:"Cote D'Ivoire (Ivory Coast)"},
  { value:'ck', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag ck", label:"Cook Islands"},
  { value:'cl', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag cl", label:"Chile"},
    { value:'cm', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag cm", label:"Cameroon"},
    { value:'cn', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag cn", label:"China"},
    { value:'co', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag co", label:"Colombia"},
    { value:'cr', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag cr", label:"Costa Rica"},
  { value:'cs', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag cs", label:"Serbia and Montenegro"},
  { value:'cu', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag cu", label:"Cuba"},
    { value:'cv', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag cv", label:"Cape Verde"},
  { value:'cx', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag cx", label:"Christmas Island"},
  { value:'cy', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag cy", label:"Cyprus"},
    { value:'cz', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag cz", label:"Czech Republic"},
  { value:'de', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag de", label:"Germany"},
    { value:'dj', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag dj", label:"Djibouti"},
    { value:'dk', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag dk", label:"Denmark"},
    { value:'dm', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag dm", label:"Dominica"},
    { value:'do', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag do", label:"Dominican Republic"},
  { value:'dz', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag dz", label:"Algeria"},
    { value:'ec', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag ec", label:"Ecuador"},
    { value:'ee', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag ee", label:"Estonia"},
    { value:'eg', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag eg", label:"Egypt"},
    { value:'eh', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag eh", label:"Western Sahara"},
  { value:'er', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag er", label:"Eritrea"},
    { value:'es', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag es", label:"Spain"},
    { value:'et', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag et", label:"Ethiopia"},
    { value:'fi', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag fi", label:"Finland"},
    { value:'fj', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag fj", label:"Fiji"},
    { value:'fk', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag fk", label:"Falkland Islands (Malvinas)"},
  { value:'fm', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag fm", label:"Federated States of Micronesia"},
  { value:'fo', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag fo", label:"Faroe Islands"},
  { value:'fr', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag fr", label:"France"},
    { value:'fx', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag fx", label:"France, Metropolitan"},
  { value:'ga', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag ga", label:"Gabon"},
    { value:'gb', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag gb", label:"Great Britain (UK)"},
  { value:'gd', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag gd", label:"Grenada"},
    { value:'ge', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag ge", label:"Georgia"},
    { value:'gf', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag gf", label:"French Guiana"},
  { value:'gh', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag gh", label:"Ghana"},
    { value:'gi', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag gi", label:"Gibraltar"},
    { value:'gl', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag gl", label:"Greenland"},
    { value:'gm', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag gm", label:"Gambia"},
    { value:'gn', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag gn", label:"Guinea"},
    { value:'gp', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag gp", label:"Guadeloupe"},
    { value:'gq', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag gq", label:"Equatorial Guinea"},
  { value:'gr', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag gr", label:"Greece"},
    { value:'gs', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag gs", label:"S. Georgia and S. Sandwich Islands"},
  { value:'gt', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag gt", label:"Guatemala"},
    { value:'gu', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag gu", label:"Guam"},
    { value:'gw', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag gw", label:"Guinea-Bissau"},
    { value:'gy', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag gy", label:"Guyana"},
    { value:'hk', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag hk", label:"Hong Kong"},
  { value:'hm', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag hm", label:"Heard Island and McDonald Islands"},
  { value:'hn', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag hn", label:"Honduras"},
    { value:'hr', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag hr", label:"Croatia (Hrvatska)"},
    { value:'ht', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag ht", label:"Haiti"},
    { value:'hu', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag hu", label:"Hungary"},
    { value:'id', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag id", label:"Indonesia"},
    { value:'ie', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag ie", label:"Ireland"},
    { value:'il', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag il", label:"Israel"},
    { value:'in', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag in", label:"India"},
    { value:'io', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag io", label:"British Indian Ocean Territory"},
  { value:'iq', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag iq", label:"Iraq"},
    { value:'ir', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag ir", label:"Iran"},
    { value:'is', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag is", label:"Iceland"},
    { value:'it', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag it", label:"Italy"},
    { value:'jm', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag jm", label:"Jamaica"},
    { value:'jo', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag jo", label:"Jordan"},
    { value:'jp', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag jp", label:"Japan"},
    { value:'ke', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag ke", label:"Kenya"},
    { value:'kg', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag kg", label:"Kyrgyzstan"},
    { value:'kh', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag kh", label:"Cambodia"},
    { value:'ki', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag ki", label:"Kiribati"},
    { value:'km', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag km", label:"Comoros"},
    { value:'kn', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag kn", label:"Saint Kitts and Nevis"},
  { value:'kp', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag kp", label:"Korea (North)"},
    { value:'kr', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag kr", label:"Korea (South)"},
    { value:'kw', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag kw", label:"Kuwait"},
    { value:'ky', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag ky", label:"Cayman Islands"},
  { value:'kz', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag kz", label:"Kazakhstan"},
    { value:'la', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag la", label:"Laos"},
    { value:'lb', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag lb", label:"Lebanon"},
    { value:'lc', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag lc", label:"Saint Lucia"},
  { value:'li', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag li", label:"Liechtenstein"},
    { value:'lk', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag lk", label:"Sri Lanka"},
  { value:'lr', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag lr", label:"Liberia"},
    { value:'ls', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag ls", label:"Lesotho"},
    { value:'lt', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag lt", label:"Lithuania"},
    { value:'lu', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag lu", label:"Luxembourg"},
    { value:'lv', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag lv", label:"Latvia"},
    { value:'ly', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag ly", label:"Libya"},
    { value:'ma', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag ma", label:"Morocco"},
    { value:'mc', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag mc", label:"Monaco"},
    { value:'md', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag md", label:"Moldova"},
    { value:'mg', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag mg", label:"Madagascar"},
    { value:'mh', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag mh", label:"Marshall Islands"},
  { value:'mk', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag mk", label:"Macedonia"},
    { value:'ml', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag ml", label:"Mali"},
    { value:'mm', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag mm", label:"Myanmar"},
    { value:'mn', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag mn", label:"Mongolia"},
    { value:'mo', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag mo", label:"Macao"},
    { value:'mp', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag mp", label:"Northern Mariana Islands"},
  { value:'mq', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag mq", label:"Martinique"},
    { value:'mr', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag mr", label:"Mauritania"},
    { value:'ms', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag ms", label:"Montserrat"},
    { value:'mt', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag mt", label:"Malta"},
    { value:'mu', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag mu", label:"Mauritius"},
    { value:'mv', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag mv", label:"Maldives"},
    { value:'mw', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag mw", label:"Malawi"},
    { value:'mx', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag mx", label:"Mexico"},
    { value:'my', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag my", label:"Malaysia"},
    { value:'mz', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag mz", label:"Mozambique"},
    { value:'na', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag na", label:"Namibia"},
    { value:'nc', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag nc", label:"New Caledonia"},
  { value:'ne', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag ne", label:"Niger"},
    { value:'nf', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag nf", label:"Norfolk Island"},
  { value:'ng', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag ng", label:"Nigeria"},
    { value:'ni', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag ni", label:"Nicaragua"},
    { value:'nl', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag nl", label:"Netherlands"},
    { value:'no', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag no", label:"Norway"},
    { value:'np', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag np", label:"Nepal"},
    { value:'nr', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag nr", label:"Nauru"},
    { value:'nu', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag nu", label:"Niue"},
    { value:'nz', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag nz", label:"New Zealand (Aotearoa)"},
  { value:'om', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag om", label:"Oman"},
    { value:'pa', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag pa", label:"Panama"},
    { value:'pe', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag pe", label:"Peru"},
    { value:'pf', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag pf", label:"French Polynesia"},
  { value:'pg', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag pg", label:"Papua New Guinea"},
  { value:'ph', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag ph", label:"Philippines"},
    { value:'pk', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag pk", label:"Pakistan"},
    { value:'pl', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag pl", label:"Poland"},
    { value:'pm', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag pm", label:"Saint Pierre and Miquelon"},
  { value:'pn', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag pn", label:"Pitcairn"},
    { value:'pr', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag pr", label:"Puerto Rico"},
  { value:'ps', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag ps", label:"Palestinian Territory"},
  { value:'pt', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag pt", label:"Portugal"},
    { value:'pw', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag pw", label:"Palau"},
    { value:'py', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag py", label:"Paraguay"},
    { value:'qa', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag qa", label:"Qatar"},
    { value:'re', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag re", label:"Reunion"},
    { value:'ro', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag ro", label:"Romania"},
    { value:'ru', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag ru", label:"Russian Federation"},
  { value:'rw', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag rw", label:"Rwanda"},
    { value:'sa', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag sa", label:"Saudi Arabia"},
  { value:'sb', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag sb", label:"Solomon Islands"},
  { value:'sc', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag sc", label:"Seychelles"},
    { value:'sd', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag sd", label:"Sudan"},
    { value:'se', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag se", label:"Sweden"},
    { value:'sg', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag sg", label:"Singapore"},
    { value:'sh', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag sh", label:"Saint Helena"},
  { value:'si', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag si", label:"Slovenia"},
    { value:'sj', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag sj", label:"Svalbard and Jan Mayen"},
  { value:'sk', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag sk", label:"Slovakia"},
    { value:'sl', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag sl", label:"Sierra Leone"},
  { value:'sm', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag sm", label:"San Marino"},
  { value:'sn', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag sn", label:"Senegal"},
    { value:'so', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag so", label:"Somalia"},
    { value:'sr', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag sr", label:"Suriname"},
    { value:'st', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag st", label:"Sao Tome and Principe"},
  { value:'su', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag su", label:"USSR (former)"},
    { value:'sv', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag sv", label:"El Salvador"},
  { value:'sy', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag sy", label:"Syria"},
    { value:'sz', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag sz", label:"Swaziland"},
    { value:'tc', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag tc", label:"Turks and Caicos Islands"},
  { value:'td', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag td", label:"Chad"},
    { value:'tf', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag tf", label:"French Southern Territories"},
  { value:'tg', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag tg", label:"Togo"},
    { value:'th', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag th", label:"Thailand"},
    { value:'tj', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag tj", label:"Tajikistan"},
    { value:'tk', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag tk", label:"Tokelau"},
    { value:'tl', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag tl", label:"Timor-Leste"},
    { value:'tm', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag tm", label:"Turkmenistan"},
    { value:'tn', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag tn", label:"Tunisia"},
    { value:'to', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag to", label:"Tonga"},
    { value:'tp', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag tp", label:"East Timor"},
  { value:'tr', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag tr", label:"Turkey"},
    { value:'tt', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag tt", label:"Trinidad and Tobago"},
  { value:'tv', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag tv", label:"Tuvalu"},
    { value:'tw', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag tw", label:"Taiwan"},
    { value:'tz', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag tz", label:"Tanzania"},
    { value:'ua', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag ua", label:"Ukraine"},
    { value:'ug', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag ug", label:"Uganda"},
    { value:'uk', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag uk", label:"United Kingdom"},
  { value:'um', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag um", label:"United States Minor Outlying Islands"},
  { value:'us', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag us", label:"United States"},
  { value:'uy', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag uy", label:"Uruguay"},
    { value:'uz', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag uz", label:"Uzbekistan"},
    { value:'va', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag va", label:"Vatican City State (Holy See)"},
{ value:'vc', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag vc", label:"Saint Vincent and the Grenadines"},
{ value:'ve', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag ve", label:"Venezuela"},
  { value:'vg', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag vg", label:"Virgin Islands (British)"},
{ value:'vi', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag vi", label:"Virgin Islands (U.S.)"},
{ value:'vn', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag vn", label:"Viet Nam"},
{ value:'vu', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag vu", label:"Vanuatu"},
  { value:'wf', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag wf", label:"Wallis and Futuna"},
{ value:'ws', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag ws", label:"Samoa"},
  { value:'ye', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag ye", label:"Yemen"},
  { value:'yt', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag yt", label:"Mayotte"},
  { value:'yu', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag yu", label:"Yugoslavia (former)"},
  { value:'za', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag za", label:"South Africa"},
{ value:'zm', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag zm", label:"Zambia"},
  { value:'zr', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag zr", label:"Zaire (former)"},
  { value:'zw', flag:"http://www.marghoobsuleman.com/mywork/jcomponents/image-dropdown/samples/images/msdropdown/icons/blank.gif",  imageCSS:"flag zw", label:"Zimbabwe"},
];
