module.exports = [

  { value:'ad',   imageCSS:"flag ad", label:"Andorra"},
  { value:'ae',   imageCSS:"flag ae", label:"United Arab Emirates"},
  { value:'af',   imageCSS:"flag af", label:"Afghanistan"},
    { value:'ag',   imageCSS:"flag ag", label:"Antigua and Barbuda"},
  { value:'ai',   imageCSS:"flag ai", label:"Anguilla"},
    { value:'al',   imageCSS:"flag al", label:"Albania"},
    { value:'am',   imageCSS:"flag am", label:"Armenia"},
    { value:'an',   imageCSS:"flag an", label:"Netherlands Antilles"},
  { value:'ao',   imageCSS:"flag ao", label:"Angola"},
    { value:'aq',   imageCSS:"flag aq", label:"Antarctica"},
    { value:'ar',   imageCSS:"flag ar", label:"Argentina"},
    { value:'as',   imageCSS:"flag as", label:"American Samoa"},
  { value:'at',   imageCSS:"flag at", label:"Austria"},
    { value:'au',   imageCSS:"flag au", label:"Australia"},
    { value:'aw',   imageCSS:"flag aw", label:"Aruba"},
    { value:'ax',   imageCSS:"flag ax", label:"Aland Islands"},
  { value:'az',   imageCSS:"flag az", label:"Azerbaijan"},
    { value:'ba',   imageCSS:"flag ba", label:"Bosnia and Herzegovina"},
  { value:'bb',   imageCSS:"flag bb", label:"Barbados"},
    { value:'bd',   imageCSS:"flag bd", label:"Bangladesh"},
    { value:'be',   imageCSS:"flag be", label:"Belgium"},
    { value:'bf',   imageCSS:"flag bf", label:"Burkina Faso"},
  { value:'bg',   imageCSS:"flag bg", label:"Bulgaria"},
    { value:'bh',   imageCSS:"flag bh", label:"Bahrain"},
    { value:'bi',   imageCSS:"flag bi", label:"Burundi"},
    { value:'bj',   imageCSS:"flag bj", label:"Benin"},
    { value:'bm',   imageCSS:"flag bm", label:"Bermuda"},
    { value:'bn',   imageCSS:"flag bn", label:"Brunei Darussalam"},
  { value:'bo',   imageCSS:"flag bo", label:"Bolivia"},
    { value:'br',   imageCSS:"flag br", label:"Brazil"},
    { value:'bs',   imageCSS:"flag bs", label:"Bahamas"},
    { value:'bt',   imageCSS:"flag bt", label:"Bhutan"},
    { value:'bv',   imageCSS:"flag bv", label:"Bouvet Island"},
  { value:'bw',   imageCSS:"flag bw", label:"Botswana"},
    { value:'by',   imageCSS:"flag by", label:"Belarus"},
    { value:'bz',   imageCSS:"flag bz", label:"Belize"},
    { value:'ca',   imageCSS:"flag ca", label:"Canada"},
    { value:'cc',   imageCSS:"flag cc", label:"Cocos (Keeling) Islands"},
  { value:'cd',   imageCSS:"flag cd", label:"Democratic Republic of the Congo"},
  { value:'cf',   imageCSS:"flag cf", label:"Central African Republic"},
  { value:'cg',   imageCSS:"flag cg", label:"Congo"},
    { value:'ch',   imageCSS:"flag ch", label:"Switzerland"},
    { value:'ci',   imageCSS:"flag ci", label:"Cote D'Ivoire (Ivory Coast)"},
  { value:'ck',   imageCSS:"flag ck", label:"Cook Islands"},
  { value:'cl',   imageCSS:"flag cl", label:"Chile"},
    { value:'cm',   imageCSS:"flag cm", label:"Cameroon"},
    { value:'cn',   imageCSS:"flag cn", label:"China"},
    { value:'co',   imageCSS:"flag co", label:"Colombia"},
    { value:'cr',   imageCSS:"flag cr", label:"Costa Rica"},
  { value:'cs',   imageCSS:"flag cs", label:"Serbia and Montenegro"},
  { value:'cu',   imageCSS:"flag cu", label:"Cuba"},
    { value:'cv',   imageCSS:"flag cv", label:"Cape Verde"},
  { value:'cx',   imageCSS:"flag cx", label:"Christmas Island"},
  { value:'cy',   imageCSS:"flag cy", label:"Cyprus"},
    { value:'cz',   imageCSS:"flag cz", label:"Czech Republic"},
  { value:'de',   imageCSS:"flag de", label:"Germany"},
    { value:'dj',   imageCSS:"flag dj", label:"Djibouti"},
    { value:'dk',   imageCSS:"flag dk", label:"Denmark"},
    { value:'dm',   imageCSS:"flag dm", label:"Dominica"},
    { value:'do',   imageCSS:"flag do", label:"Dominican Republic"},
  { value:'dz',   imageCSS:"flag dz", label:"Algeria"},
    { value:'ec',   imageCSS:"flag ec", label:"Ecuador"},
    { value:'ee',   imageCSS:"flag ee", label:"Estonia"},
    { value:'eg',   imageCSS:"flag eg", label:"Egypt"},
    { value:'eh',   imageCSS:"flag eh", label:"Western Sahara"},
  { value:'er',   imageCSS:"flag er", label:"Eritrea"},
    { value:'es',   imageCSS:"flag es", label:"Spain"},
    { value:'et',   imageCSS:"flag et", label:"Ethiopia"},
    { value:'fi',   imageCSS:"flag fi", label:"Finland"},
    { value:'fj',   imageCSS:"flag fj", label:"Fiji"},
    { value:'fk',   imageCSS:"flag fk", label:"Falkland Islands (Malvinas)"},
  { value:'fm',   imageCSS:"flag fm", label:"Federated States of Micronesia"},
  { value:'fo',   imageCSS:"flag fo", label:"Faroe Islands"},
  { value:'fr',   imageCSS:"flag fr", label:"France"},
    { value:'fx',   imageCSS:"flag fx", label:"France, Metropolitan"},
  { value:'ga',   imageCSS:"flag ga", label:"Gabon"},
    { value:'gb',   imageCSS:"flag gb", label:"Great Britain (UK)"},
  { value:'gd',   imageCSS:"flag gd", label:"Grenada"},
    { value:'ge',   imageCSS:"flag ge", label:"Georgia"},
    { value:'gf',   imageCSS:"flag gf", label:"French Guiana"},
  { value:'gh',   imageCSS:"flag gh", label:"Ghana"},
    { value:'gi',   imageCSS:"flag gi", label:"Gibraltar"},
    { value:'gl',   imageCSS:"flag gl", label:"Greenland"},
    { value:'gm',   imageCSS:"flag gm", label:"Gambia"},
    { value:'gn',   imageCSS:"flag gn", label:"Guinea"},
    { value:'gp',   imageCSS:"flag gp", label:"Guadeloupe"},
    { value:'gq',   imageCSS:"flag gq", label:"Equatorial Guinea"},
  { value:'gr',   imageCSS:"flag gr", label:"Greece"},
    { value:'gs',   imageCSS:"flag gs", label:"S. Georgia and S. Sandwich Islands"},
  { value:'gt',   imageCSS:"flag gt", label:"Guatemala"},
    { value:'gu',   imageCSS:"flag gu", label:"Guam"},
    { value:'gw',   imageCSS:"flag gw", label:"Guinea-Bissau"},
    { value:'gy',   imageCSS:"flag gy", label:"Guyana"},
    { value:'hk',   imageCSS:"flag hk", label:"Hong Kong"},
  { value:'hm',   imageCSS:"flag hm", label:"Heard Island and McDonald Islands"},
  { value:'hn',   imageCSS:"flag hn", label:"Honduras"},
    { value:'hr',   imageCSS:"flag hr", label:"Croatia (Hrvatska)"},
    { value:'ht',   imageCSS:"flag ht", label:"Haiti"},
    { value:'hu',   imageCSS:"flag hu", label:"Hungary"},
    { value:'id',   imageCSS:"flag id", label:"Indonesia"},
    { value:'ie',   imageCSS:"flag ie", label:"Ireland"},
    { value:'il',   imageCSS:"flag il", label:"Israel"},
    { value:'in',   imageCSS:"flag in", label:"India"},
    { value:'io',   imageCSS:"flag io", label:"British Indian Ocean Territory"},
  { value:'iq',   imageCSS:"flag iq", label:"Iraq"},
    { value:'ir',   imageCSS:"flag ir", label:"Iran"},
    { value:'is',   imageCSS:"flag is", label:"Iceland"},
    { value:'it',   imageCSS:"flag it", label:"Italy"},
    { value:'jm',   imageCSS:"flag jm", label:"Jamaica"},
    { value:'jo',   imageCSS:"flag jo", label:"Jordan"},
    { value:'jp',   imageCSS:"flag jp", label:"Japan"},
    { value:'ke',   imageCSS:"flag ke", label:"Kenya"},
    { value:'kg',   imageCSS:"flag kg", label:"Kyrgyzstan"},
    { value:'kh',   imageCSS:"flag kh", label:"Cambodia"},
    { value:'ki',   imageCSS:"flag ki", label:"Kiribati"},
    { value:'km',   imageCSS:"flag km", label:"Comoros"},
    { value:'kn',   imageCSS:"flag kn", label:"Saint Kitts and Nevis"},
  { value:'kp',   imageCSS:"flag kp", label:"Korea (North)"},
    { value:'kr',   imageCSS:"flag kr", label:"Korea (South)"},
    { value:'kw',   imageCSS:"flag kw", label:"Kuwait"},
    { value:'ky',   imageCSS:"flag ky", label:"Cayman Islands"},
  { value:'kz',   imageCSS:"flag kz", label:"Kazakhstan"},
    { value:'la',   imageCSS:"flag la", label:"Laos"},
    { value:'lb',   imageCSS:"flag lb", label:"Lebanon"},
    { value:'lc',   imageCSS:"flag lc", label:"Saint Lucia"},
  { value:'li',   imageCSS:"flag li", label:"Liechtenstein"},
    { value:'lk',   imageCSS:"flag lk", label:"Sri Lanka"},
  { value:'lr',   imageCSS:"flag lr", label:"Liberia"},
    { value:'ls',   imageCSS:"flag ls", label:"Lesotho"},
    { value:'lt',   imageCSS:"flag lt", label:"Lithuania"},
    { value:'lu',   imageCSS:"flag lu", label:"Luxembourg"},
    { value:'lv',   imageCSS:"flag lv", label:"Latvia"},
    { value:'ly',   imageCSS:"flag ly", label:"Libya"},
    { value:'ma',   imageCSS:"flag ma", label:"Morocco"},
    { value:'mc',   imageCSS:"flag mc", label:"Monaco"},
    { value:'md',   imageCSS:"flag md", label:"Moldova"},
    { value:'mg',   imageCSS:"flag mg", label:"Madagascar"},
    { value:'mh',   imageCSS:"flag mh", label:"Marshall Islands"},
  { value:'mk',   imageCSS:"flag mk", label:"Macedonia"},
    { value:'ml',   imageCSS:"flag ml", label:"Mali"},
    { value:'mm',   imageCSS:"flag mm", label:"Myanmar"},
    { value:'mn',   imageCSS:"flag mn", label:"Mongolia"},
    { value:'mo',   imageCSS:"flag mo", label:"Macao"},
    { value:'mp',   imageCSS:"flag mp", label:"Northern Mariana Islands"},
  { value:'mq',   imageCSS:"flag mq", label:"Martinique"},
    { value:'mr',   imageCSS:"flag mr", label:"Mauritania"},
    { value:'ms',   imageCSS:"flag ms", label:"Montserrat"},
    { value:'mt',   imageCSS:"flag mt", label:"Malta"},
    { value:'mu',   imageCSS:"flag mu", label:"Mauritius"},
    { value:'mv',   imageCSS:"flag mv", label:"Maldives"},
    { value:'mw',   imageCSS:"flag mw", label:"Malawi"},
    { value:'mx',   imageCSS:"flag mx", label:"Mexico"},
    { value:'my',   imageCSS:"flag my", label:"Malaysia"},
    { value:'mz',   imageCSS:"flag mz", label:"Mozambique"},
    { value:'na',   imageCSS:"flag na", label:"Namibia"},
    { value:'nc',   imageCSS:"flag nc", label:"New Caledonia"},
  { value:'ne',   imageCSS:"flag ne", label:"Niger"},
    { value:'nf',   imageCSS:"flag nf", label:"Norfolk Island"},
  { value:'ng',   imageCSS:"flag ng", label:"Nigeria"},
    { value:'ni',   imageCSS:"flag ni", label:"Nicaragua"},
    { value:'nl',   imageCSS:"flag nl", label:"Netherlands"},
    { value:'no',   imageCSS:"flag no", label:"Norway"},
    { value:'np',   imageCSS:"flag np", label:"Nepal"},
    { value:'nr',   imageCSS:"flag nr", label:"Nauru"},
    { value:'nu',   imageCSS:"flag nu", label:"Niue"},
    { value:'nz',   imageCSS:"flag nz", label:"New Zealand (Aotearoa)"},
  { value:'om',   imageCSS:"flag om", label:"Oman"},
    { value:'pa',   imageCSS:"flag pa", label:"Panama"},
    { value:'pe',   imageCSS:"flag pe", label:"Peru"},
    { value:'pf',   imageCSS:"flag pf", label:"French Polynesia"},
  { value:'pg',   imageCSS:"flag pg", label:"Papua New Guinea"},
  { value:'ph',   imageCSS:"flag ph", label:"Philippines"},
    { value:'pk',   imageCSS:"flag pk", label:"Pakistan"},
    { value:'pl',   imageCSS:"flag pl", label:"Poland"},
    { value:'pm',   imageCSS:"flag pm", label:"Saint Pierre and Miquelon"},
  { value:'pn',   imageCSS:"flag pn", label:"Pitcairn"},
    { value:'pr',   imageCSS:"flag pr", label:"Puerto Rico"},
  { value:'ps',   imageCSS:"flag ps", label:"Palestinian Territory"},
  { value:'pt',   imageCSS:"flag pt", label:"Portugal"},
    { value:'pw',   imageCSS:"flag pw", label:"Palau"},
    { value:'py',   imageCSS:"flag py", label:"Paraguay"},
    { value:'qa',   imageCSS:"flag qa", label:"Qatar"},
    { value:'re',   imageCSS:"flag re", label:"Reunion"},
    { value:'ro',   imageCSS:"flag ro", label:"Romania"},
    { value:'ru',   imageCSS:"flag ru", label:"Russian Federation"},
  { value:'rw',   imageCSS:"flag rw", label:"Rwanda"},
    { value:'sa',   imageCSS:"flag sa", label:"Saudi Arabia"},
  { value:'sb',   imageCSS:"flag sb", label:"Solomon Islands"},
  { value:'sc',   imageCSS:"flag sc", label:"Seychelles"},
    { value:'sd',   imageCSS:"flag sd", label:"Sudan"},
    { value:'se',   imageCSS:"flag se", label:"Sweden"},
    { value:'sg',   imageCSS:"flag sg", label:"Singapore"},
    { value:'sh',   imageCSS:"flag sh", label:"Saint Helena"},
  { value:'si',   imageCSS:"flag si", label:"Slovenia"},
    { value:'sj',   imageCSS:"flag sj", label:"Svalbard and Jan Mayen"},
  { value:'sk',   imageCSS:"flag sk", label:"Slovakia"},
    { value:'sl',   imageCSS:"flag sl", label:"Sierra Leone"},
  { value:'sm',   imageCSS:"flag sm", label:"San Marino"},
  { value:'sn',   imageCSS:"flag sn", label:"Senegal"},
    { value:'so',   imageCSS:"flag so", label:"Somalia"},
    { value:'sr',   imageCSS:"flag sr", label:"Suriname"},
    { value:'st',   imageCSS:"flag st", label:"Sao Tome and Principe"},
  { value:'su',   imageCSS:"flag su", label:"USSR (former)"},
    { value:'sv',   imageCSS:"flag sv", label:"El Salvador"},
  { value:'sy',   imageCSS:"flag sy", label:"Syria"},
    { value:'sz',   imageCSS:"flag sz", label:"Swaziland"},
    { value:'tc',   imageCSS:"flag tc", label:"Turks and Caicos Islands"},
  { value:'td',   imageCSS:"flag td", label:"Chad"},
    { value:'tf',   imageCSS:"flag tf", label:"French Southern Territories"},
  { value:'tg',   imageCSS:"flag tg", label:"Togo"},
    { value:'th',   imageCSS:"flag th", label:"Thailand"},
    { value:'tj',   imageCSS:"flag tj", label:"Tajikistan"},
    { value:'tk',   imageCSS:"flag tk", label:"Tokelau"},
    { value:'tl',   imageCSS:"flag tl", label:"Timor-Leste"},
    { value:'tm',   imageCSS:"flag tm", label:"Turkmenistan"},
    { value:'tn',   imageCSS:"flag tn", label:"Tunisia"},
    { value:'to',   imageCSS:"flag to", label:"Tonga"},
    { value:'tp',   imageCSS:"flag tp", label:"East Timor"},
  { value:'tr',   imageCSS:"flag tr", label:"Turkey"},
    { value:'tt',   imageCSS:"flag tt", label:"Trinidad and Tobago"},
  { value:'tv',   imageCSS:"flag tv", label:"Tuvalu"},
    { value:'tw',   imageCSS:"flag tw", label:"Taiwan"},
    { value:'tz',   imageCSS:"flag tz", label:"Tanzania"},
    { value:'ua',   imageCSS:"flag ua", label:"Ukraine"},
    { value:'ug',   imageCSS:"flag ug", label:"Uganda"},
    { value:'uk',   imageCSS:"flag uk", label:"United Kingdom"},
  { value:'um',   imageCSS:"flag um", label:"United States Minor Outlying Islands"},
  { value:'us',   imageCSS:"flag us", label:"United States"},
  { value:'uy',   imageCSS:"flag uy", label:"Uruguay"},
    { value:'uz',   imageCSS:"flag uz", label:"Uzbekistan"},
    { value:'va',   imageCSS:"flag va", label:"Vatican City State (Holy See)"},
{ value:'vc',   imageCSS:"flag vc", label:"Saint Vincent and the Grenadines"},
{ value:'ve',   imageCSS:"flag ve", label:"Venezuela"},
  { value:'vg',   imageCSS:"flag vg", label:"Virgin Islands (British)"},
{ value:'vi',   imageCSS:"flag vi", label:"Virgin Islands (U.S.)"},
{ value:'vn',   imageCSS:"flag vn", label:"Viet Nam"},
{ value:'vu',   imageCSS:"flag vu", label:"Vanuatu"},
  { value:'wf',   imageCSS:"flag wf", label:"Wallis and Futuna"},
{ value:'ws',   imageCSS:"flag ws", label:"Samoa"},
  { value:'ye',   imageCSS:"flag ye", label:"Yemen"},
  { value:'yt',   imageCSS:"flag yt", label:"Mayotte"},
  { value:'yu',   imageCSS:"flag yu", label:"Yugoslavia (former)"},
  { value:'za',   imageCSS:"flag za", label:"South Africa"},
{ value:'zm',   imageCSS:"flag zm", label:"Zambia"},
  { value:'zr',   imageCSS:"flag zr", label:"Zaire (former)"},
  { value:'zw',   imageCSS:"flag zw", label:"Zimbabwe"},
];
